#define REPLACE_EVENT(oldEvent, newEvent) class oldEvent { CBA_Event = newEvent; }

class Events {
    REPLACE_EVENT(AIVehInit,CBA_EVENT_SERVER_INIT_AI_VEHICLE);
    REPLACE_EVENT(HQPlaced,CBA_EVENT_CLIENT_HQ_PLACED);
    REPLACE_EVENT(RebelControlCreated,CBA_EVENT_SERVER_CREATE_REBEL_CONTROL);
    REPLACE_EVENT(markerChange,CBA_EVENT_SERVER_MARKER_CHANGE);
    REPLACE_EVENT(vehicleBoxRestore,CBA_EVENT_CLIENT_VEHICLE_BOX_RESTORE);
    REPLACE_EVENT(civInit,CBA_EVENT_SERVER_INIT_CIVILIAN_UNIT);
    REPLACE_EVENT(civVehInit,CBA_EVENT_SERVER_INIT_CIVILIAN_VEHICLE);
    REPLACE_EVENT(locationSpawned,CBA_EVENT_SERVER_SPAWN_LOCATION);
    REPLACE_EVENT(AIInit,CBA_EVENT_SERVER_INIT_AI_UNIT);
    REPLACE_EVENT(Undercover,CBA_EVENT_CLIENT_UNDERCOVER_CHANGED);
};
